//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Cards = new HashSet<Card>();
            this.Purchases = new HashSet<Purchase>();
        }
    
        public string custId { get; set; }
        public string custName { get; set; }
        public string custEmail { get; set; }
        public string custPassword { get; set; }
        public System.DateTime custDob { get; set; }
        public string custPhoneNo { get; set; }
        public string custGender { get; set; }
        public string custPhoto { get; set; }
        public string custStatus { get; set; }
        public string signature { get; set; }
        public Nullable<int> loginNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
