//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseMenu
    {
        public string menuId { get; set; }
        public string purchaseNo { get; set; }
        public int menuQty { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
