//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string scheduleNo { get; set; }
        public string movieId { get; set; }
        public string hallNo { get; set; }
        public System.DateTime scheduleDateTime { get; set; }
    }
}
