//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public string staffId { get; set; }
        public string staffName { get; set; }
        public string staffEmail { get; set; }
        public string staffPassword { get; set; }
        public string staffIC { get; set; }
        public string staffGender { get; set; }
        public string staffPhoneNo { get; set; }
        public string staffPhoto { get; set; }
        public string position { get; set; }
        public string staffStatus { get; set; }
    }
}
