//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string ticketNo { get; set; }
        public string purchaseNo { get; set; }
        public string scheduleNo { get; set; }
        public string ticketCategory { get; set; }
        public decimal ticketPrice { get; set; }
        public string seatNo { get; set; }
        public short id { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
